config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  resources :registrations
  resources :logins
  resources :users 
  get '/club', to: 'users#fight_club'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/registration.rb
class Registration < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :set_current_user
    private
    def set_current_user
      if session[:user_id]
        @user_connected = User.find(session[:user_id])
      end
    end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  
  def index 
    @current_user = User.new
  end
        
  def create
    @current_user = User.where(email: params[:user][:email].downcase).first
    puts @current_user
    if @current_user && @current_user.authenticate(params[:user][:password])
      session[:user_id] = @current_user.id
      redirect_to '/club', flash: {notice: "Vous êtes maintenant connecté"}
    elsif @current_user
      session[:user_id] = nil
      puts "Pas bon mot de passe"
      redirect_to '/logins', flash: {notice: "Le mot de passe est faux, veuillez rééssayer"}
    else 
      session[:user_id] = nil
      puts "Email n'existe pas"
      redirect_to '/logins', flash: {notice: "Mauvais email, veuillez rééssayer"}
    end
  end

  def destroy
    
  end
  def show
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  
  def index 
    @user = User.new
  end
  
  def create 
    @user = User.create(first_name: params[:user][:first_name], last_name: params[:user][:last_name], email: params[:user][:email], password: params[:user][:password])
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/users'
    else
      flash[:notice] = @user.errors.full_messages
      redirect_to '/registrations'
    end
  end

  def show
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index 
	end

	def create 
		session[:user_id] = nil
		redirect_to '/users'
	end

	def fight_club 
		@user=User.all
		unless session[:user_id]
			redirect_to '/users', flash: {notice: "Accès interdit au club sans être connecté"}
		end
	end

	def show
		@current_user = User.find(params[:id])
		unless session[:user_id]
			redirect_to '/users', flash: {notice: "Accès interdit au profil quand non conecté"}
		end
	end
	
	def edit 
		@current_user = User.find(params[:id])
		unless session[:user_id] == @current_user.id
			if session[:user_id]
				redirect_to '/club', flash: {notice: "Accès interdit à l'édition du profil des autres"}
			else
				redirect_to '/users', flash: {notice: "Accès interdit au profil quand non connecté"}
			end 
		end
	end

	def update
		@current_user = User.find(params[:id])
		@current_user = @current_user.update_attributes(first_name: params[:user][:first_name], last_name: params[:user][:last_name], email: params[:user][:email])
		if @current_user
			flash[:notice]= "Vous avez bien modifié votre profil"
			redirect_to '/club'
		else
			flash[:notice]= "Accès interdit au profil quand non connecté"
			redirect_to '/users/' + params[:id].to_s + '/edit' 
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def flash_class(level)
        case level
            when :notice then "alert alert-info"
            when :success then "alert alert-success"
            when :error then "alert alert-error"
            when :alert then "alert alert-error"
        end
    end
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="flex-fill">
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="/users">Home</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

  	<% if @user_connected %>
    	<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav">
			<%= link_to "Le club :)", '/club', method: :get, class: "nav-link" %>
			<%= link_to "MaJ des données", '/users/'+session[:user_id].to_s+'/edit', method: :get, class: "nav-link" %>
    	<%= link_to "Déconnexion", '/users', method: :post, class: "nav-link" %>
		</ul>
		</div>

    <% else %>
		<div class="collapse navbar-collapse" id="navbarNav">
		<ul class="navbar-nav">
    	<%= link_to "Enregistrement", registrations_path, class: "nav-link" %>
    	<%= link_to "Connexion", logins_path, class: "nav-link" %>
		</ul>
		</div>

    <% end %>

	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/index.html.erb
<%= render "layouts/header" %>

<body class="bg-secondary text-light align-items-stretch ">
	<p id="notice"><%= notice %></p>
	<div class="container-fluid">
		<h3><br/>Login</h3>
		<div class="form-row">

		<%= form_for @current_user, url: "/logins", method: :post, html: {class: "col-md-6"} do |f| %>
			
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label "Entrez votre email" %>
					<%= f.text_field :email, placeholder: 'Email', class: "form-control" %>
				</div>			
			</div> 

            <div class="col-md-6">
				<div class="form-group">
					<%= f.label "Entrez votre mot de passe" %>
					<%= f.password_field :password, placeholder: 'Mot de passe', class: "form-control" %>
				</div>			
			</div> 

			<div class="col-md-12 form-group  text-light">
				<%= f.submit "Valider", class: "btn btn-outline-success bg-info col-md-12 align-items-stretch	text-light" %>
			</div>
		<% end %>
		</div>
	</div>
</body>

app/views/users/edit.html.erb
<%= render "layouts/header" %>

<body class="bg-secondary text-light align-items-stretch ">
	<div class="container-fluid text-warning">
	<p id="notice"><%= notice %></p>
	</div>
	<div class="container-fluid">
		<h3><br/>Mise à jour de tes données</h3>
		<div class="form-row">

		<%= form_for @user_connected, url: {action: "update"}, html: {class: "col-md-6"} do |f| %>
			
			<div class="col-md-12">
				<div class="form-group">
					<%= f.label "Entrez ton Prénom"%>
					<%= f.text_field :first_name, placeholder: 'William', class: "form-control" %>
				</div>			
			</div> 

			<div class="col-md-12">
				<div class="form-group">
					<%= f.label "Entrez ton nom"%>
					<%= f.text_field :last_name, placeholder: 'Blazkowicz', class: "form-control" %>
				</div>			
			</div> 

			<div class="col-md-12">
				<div class="form-group">
					<%= f.label "Entrez ton email" %>
					<%= f.text_field :email, placeholder: 'William.Blascovitch@killnazies.com', class: "form-control" %>
					
				</div>			
			</div>

			<div class="col-md-12 form-group  text-light">
				<%= f.submit "Mettre à jour", class: "form-control btn btn-outline-success bg-info align-items-stretch	text-light" %>
			</div>
		<% end %>
		</div>
	 </div>
</div>
</div>
</div>

</body>

app/views/users/fight_club.html.erb
<%= render "layouts/header" %>

<body class="bg-secondary text-light d-flex align-items-stretch flex-wrap">

<div class="container-fluid align-items-stretch bg-secondary">
<div class= "text-light  d-flex align-content-end flex-wrap ">
<div class="center jumbotron bg-secondary">  

	<h2>Tu as réussi à accéder au fight-club <%= @user_connected.first_name %> <%= @user_connected.last_name %></h2>
	<br/>
	<div class= "text-light  d-flex align-content-end flex-wrap ">
	<div class="center jumbotron bg-secondary">  
	 	<%=image_tag("no_photo.png", alt: "Example Image")%>
	</div>
	</div>
	<h3>Tout d'abord, petit rappel des règles:</h3>
	<h4> <ul>
		<li>La première règle du Fight Club est : il est interdit de parler du Fight Club. </li>
		<li>La seconde règle du Fight Club est : il est interdit de parler du Fight Club. </li>
		<li>Troisième règle du Fight Club : quelqu'un crie stop, quelqu'un s'écroule ou n'en peut plus, le combat est terminé. </li>
		<li>Quatrième règle : seulement deux hommes par combat. Cinquième règle : un seul combat à la fois, messieurs. </li>
		<li>Sixième règle : pas de chemise, ni de chaussures. </li>
		<li>Septième règle : les combats continueront aussi longtemps que nécessaire. </li>
		<li>Et huitième et dernière règle : si c'est votre première soirée au Fight Club, vous devez vous battre.</li>
		
	</ul></h4>
	<br/>
	<h3> Et ici, les membres de notre club</h3>
	<table class="table">
	<thead>
	  <tr>
	  	<td>ID</td>
			<td>Prénom</td>
			<td>Nom</td>            
			<td>Mail</td>
			<td>Lien vers le profil</td>
		</tr>
	</thead>
	<tbody>
	<% @user.each do |user| %>
	  <tr>
		  <td><%= user.id %></td>
		  <td><%= user.first_name  %></td>
		  <td><%= user.last_name %></td>
		  <td><%= user.email %></td>
		  <td><strong><%= link_to "Fiche de " + user.first_name + " " + user.last_name, '/users/' + user.id.to_s, method: :get%> </strong></td>
	  </tr>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render "layouts/header" %>

<body class="bg-secondary text-light d-flex align-items-stretch flex-wrap">
<div class="container-fluid text-warning">
	<p id="notice"><%= notice %></p>
</div>
<div class="container-fluid align-items-stretch bg-secondary">
<div class= "text-light  d-flex align-content-end flex-wrap ">
<div class="center jumbotron bg-secondary">       
  <% if @user_connected %>
    <div class= "text-light  d-flex align-content-end flex-wrap ">
	  <div class="center jumbotron bg-secondary">  
	 	  <%=image_tag("no_photo.png", alt: "Example Image")%>
	  </div>
	  </div>
    <h1>Bienvenue <%= @user_connected.first_name %> <%= @user_connected.last_name %>!</h1>
    <br/>
    <%= link_to "Le club secret :)", '/club', method: :get, class: "btn btn-lg btn-primary" %>
		<%= link_to "Mise à jour des données", '/users/'+session[:user_id].to_s+'/edit', method: :get, class: "btn btn-lg btn-primary" %>
    <%= link_to "Déconnexion", '/users', method: :post, class: "btn btn-lg btn-primary" %>

  <% else %>    
    <h1>Bienvenue visiteur anonyme!</h1>
    <br/>
    <h3>Enregistre ou connecte-toi pour accéder au club secret!</h3>
    <br/>
    <%= link_to "Enregistre-toi !", registrations_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Connecte-toi !", logins_path, class: "btn btn-lg btn-primary" %>
    <br/>
    <div class= "container container-table" >
	  <div class="col-xs-offset-4 vertical-center-row">  
    <br/>
	 	  <%=image_tag("index.png", alt: "Example Image", size: "750x250")%>
	  </div>
	  </div>
  <% end %>  

  
</div>
</div>
</div>

</body>

app/views/users/show.html.erb
<%= render "layouts/header" %>
<body class="bg-secondary text-light d-flex align-items-stretch flex-wrap">
<div class="container-fluid text-warning">
	<p id="notice"><%= notice %></p>
</div>
<div class="container-fluid align-items-stretch bg-secondary">
<div class= "text-light  d-flex align-content-end flex-wrap ">
<div class="center jumbotron align-items-center bg-secondary">     
  <h2> Profil de <%= @current_user.first_name %>
  <br/>
  <%=image_tag("img-fightclub.png", alt: "Example Image", size: "450x250")%>
    <ul>
      <li>Prénom : <%= @current_user.first_name %></li>
      <li>Nom : <%= @current_user.last_name%></li>
      <li>Mail : <%= @current_user.email%></li>
    <ul>
    <br/>
     
  </h2>
  <% if @user_connected.id ==@current_user.id %>
    <%= link_to "Clique ici pour modifier ton profil", '/users/' + @user_connected.id.to_s + '/edit', method: :get, class: "btn btn-lg btn-primary" %>
  <%end%> 

</div>
</div>
</div>
</body>